name: xeus-octave-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - xeus >=6,<7
  - xeus-lite >=5,<6
  - nlohmann_json
  - nlohmann_json-abi
  - octave
  - libpng
  - zlib
  - libflang
  - pcre2
  - libblas
  - liblapack
  - freetype
  - plotly
  # dragged in static libraries from image magick
  - imagemagick <7
  - libtiff
  - libpng
  - libjpeg-turbo
  - bzip2
  - libxml2
  - openjpeg
# Optional
  - octave-fuzzy-logic-toolkit
  - octave-splines
